services:

  node-exporter:
    image: prom/node-exporter
    container_name: exporter
    ports:
      - 9100:9100
    restart: unless-stopped
    networks:
      - traefik

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090
    restart: unless-stopped
    networks:
      - traefik

  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana
    restart: unless-stopped
    user: "$UID:$GID"
    environment:
      # increases the log level from info to debug
      - GF_LOG_LEVEL=debug
      - ROOT_URL=https://grafana.site.ru
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - '/opt/projekt1/custom/grafana/grafana_storage:/var/lib/grafana'
    labels:
      - "traefik.enable=true"
